# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-24 15:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('socialaccount', '0008_socialaccount_fg_points_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.URLField()),
            ],
            options={
                'ordering': ['-name'],
                'verbose_name_plural': 'Banner',
            },
        ),
        migrations.CreateModel(
            name='Betting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bet_for', models.IntegerField(default=0)),
                ('bet_against', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-bet_for'],
                'verbose_name_plural': 'Betting',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['-name'],
                'verbose_name_plural': 'Category',
            },
        ),
        migrations.CreateModel(
            name='ForeCast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=1000)),
                ('start', models.DateTimeField(default=datetime.datetime(2018, 5, 24, 21, 9, 45, 887981))),
                ('expire', models.DateTimeField()),
                ('source', models.CharField(max_length=100)),
                ('market_fee', models.IntegerField(default=0)),
                ('won', models.CharField(default='bet_for', max_length=100)),
                ('created', models.DateField()),
                ('approved', models.BooleanField(default=False)),
                ('verified', models.BooleanField(default=False)),
                ('private', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alpha.Category')),
            ],
            options={
                'ordering': ['-category'],
                'verbose_name_plural': 'Fore Cast',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_date', models.DateField(auto_now=True)),
                ('txnid', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('amount', models.FloatField(blank=True, default=0.0, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socialaccount.SocialAccount')),
            ],
            options={
                'ordering': ['-user'],
                'verbose_name_plural': 'Order',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['-name'],
                'verbose_name_plural': 'Status',
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.URLField()),
            ],
            options={
                'ordering': ['-name'],
                'verbose_name_plural': 'Sub-Category',
            },
        ),
        migrations.AddField(
            model_name='forecast',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alpha.Status'),
        ),
        migrations.AddField(
            model_name='forecast',
            name='sub_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alpha.SubCategory'),
        ),
        migrations.AddField(
            model_name='forecast',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socialaccount.SocialAccount'),
        ),
        migrations.AddField(
            model_name='betting',
            name='forecast',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alpha.ForeCast'),
        ),
        migrations.AddField(
            model_name='betting',
            name='users',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socialaccount.SocialAccount'),
        ),
    ]
