# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-12 05:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('socialaccount', '0004_auto_20180612_1110'),
    ]

    operations = [
        migrations.CreateModel(
            name='Approved',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
            options={
                'ordering': ['-name'],
                'verbose_name_plural': 'Approved',
            },
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.URLField()),
            ],
            options={
                'ordering': ['-name'],
                'verbose_name_plural': 'Banner',
            },
        ),
        migrations.CreateModel(
            name='Betting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bet_for', models.IntegerField(default=0)),
                ('bet_against', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-bet_for'],
                'verbose_name_plural': 'Points In Play',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['-name'],
                'verbose_name_plural': 'Category',
            },
        ),
        migrations.CreateModel(
            name='ForeCast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=1000)),
                ('start', models.DateTimeField(default=datetime.datetime(2018, 6, 12, 11, 11, 1, 931985))),
                ('expire', models.DateTimeField()),
                ('market_fee', models.IntegerField(default=0)),
                ('won', models.CharField(blank=True, max_length=100, null=True)),
                ('created', models.DateField()),
                ('approved', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alpha.Approved')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alpha.Category')),
            ],
            options={
                'ordering': ['-category'],
                'verbose_name_plural': 'FORECAST',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_date', models.DateField(auto_now=True)),
                ('txnid', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('amount', models.FloatField(blank=True, default=0.0, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socialaccount.SocialAccount')),
            ],
            options={
                'ordering': ['-user'],
                'verbose_name_plural': 'Order',
            },
        ),
        migrations.CreateModel(
            name='Private',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
            options={
                'ordering': ['-name'],
                'verbose_name_plural': 'Private',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['-name'],
                'verbose_name_plural': 'Status',
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('source', models.CharField(max_length=100)),
                ('image', models.URLField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alpha.Category')),
            ],
            options={
                'ordering': ['-name'],
                'verbose_name_plural': 'Sub-Category',
            },
        ),
        migrations.CreateModel(
            name='Verified',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
            options={
                'ordering': ['-name'],
                'verbose_name_plural': 'Verified',
            },
        ),
        migrations.AddField(
            model_name='forecast',
            name='private',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alpha.Private'),
        ),
        migrations.AddField(
            model_name='forecast',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alpha.Status'),
        ),
        migrations.AddField(
            model_name='forecast',
            name='sub_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alpha.SubCategory'),
        ),
        migrations.AddField(
            model_name='forecast',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socialaccount.SocialAccount'),
        ),
        migrations.AddField(
            model_name='forecast',
            name='verified',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alpha.Verified'),
        ),
        migrations.AddField(
            model_name='betting',
            name='forecast',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alpha.ForeCast'),
        ),
        migrations.AddField(
            model_name='betting',
            name='users',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socialaccount.SocialAccount'),
        ),
    ]
