# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-24 15:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alpha', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forecast',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 24, 21, 10, 5, 8766)),
        ),
    ]
