# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-09 09:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alpha', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='forecast',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 9, 9, 18, 37, 979135)),
        ),
    ]
