# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-09 12:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alpha', '0003_auto_20180509_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forecast',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='forecast',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 9, 12, 18, 37, 637142)),
        ),
    ]
