# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-10 04:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alpha', '0004_auto_20180509_1218'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['-name'],
                'verbose_name_plural': 'Category',
            },
        ),
        migrations.AlterField(
            model_name='forecast',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 10, 4, 56, 46, 43326)),
        ),
        migrations.AddField(
            model_name='forecast',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='alpha.Status'),
            preserve_default=False,
        ),
    ]
