# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-29 13:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alpha', '0004_auto_20180525_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forecast',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 29, 18, 42, 3, 512597)),
        ),
    ]
