# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-10 06:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socialaccount', '0005_auto_20180510_0600'),
        ('alpha', '0005_auto_20180510_0456'),
    ]

    operations = [
        migrations.CreateModel(
            name='Betting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bet_for', models.IntegerField()),
                ('bet_against', models.IntegerField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='status',
            options={'ordering': ['-name'], 'verbose_name_plural': 'Status'},
        ),
        migrations.AlterField(
            model_name='forecast',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 10, 6, 0, 0, 798029)),
        ),
        migrations.AddField(
            model_name='betting',
            name='forecast',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alpha.ForeCast'),
        ),
        migrations.AddField(
            model_name='betting',
            name='users',
            field=models.ManyToManyField(to='socialaccount.SocialAccount'),
        ),
    ]
