# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-29 13:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alpha', '0005_auto_20180529_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forecast',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 29, 18, 43, 10, 728945)),
        ),
    ]
