# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-20 08:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alpha', '0006_auto_20180620_1408'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitefreinds',
            name='user',
        ),
        migrations.AlterField(
            model_name='forecast',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 20, 14, 10, 54, 562420)),
        ),
        migrations.DeleteModel(
            name='InviteFreinds',
        ),
    ]
