# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-10 06:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alpha', '0006_auto_20180510_0600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forecast',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 10, 6, 1, 7, 56603)),
        ),
    ]
