# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-29 16:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alpha', '0006_auto_20180529_1843'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forecast',
            name='source',
        ),
        migrations.AddField(
            model_name='subcategory',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='alpha.Category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subcategory',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='source',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='forecast',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 29, 21, 39, 17, 812788)),
        ),
        migrations.DeleteModel(
            name='Source',
        ),
    ]
