# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-10 06:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socialaccount', '0006_auto_20180510_0601'),
        ('alpha', '0007_auto_20180510_0601'),
    ]

    operations = [
        migrations.CreateModel(
            name='BettingForecast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_points', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-forecast'],
                'verbose_name_plural': 'Betting Forecast',
            },
        ),
        migrations.AlterModelOptions(
            name='betting',
            options={'ordering': ['-bet_for'], 'verbose_name_plural': 'Betting'},
        ),
        migrations.RemoveField(
            model_name='betting',
            name='forecast',
        ),
        migrations.RemoveField(
            model_name='betting',
            name='users',
        ),
        migrations.AddField(
            model_name='betting',
            name='bet_points_against',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='betting',
            name='bet_points_for',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='betting',
            name='bet_against',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='betting',
            name='bet_for',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='forecast',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 10, 6, 37, 41, 163673)),
        ),
        migrations.AddField(
            model_name='bettingforecast',
            name='forecast',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alpha.ForeCast'),
        ),
        migrations.AddField(
            model_name='bettingforecast',
            name='users',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socialaccount.SocialAccount'),
        ),
        migrations.AddField(
            model_name='betting',
            name='betting_forecast',
            field=models.ManyToManyField(to='alpha.BettingForecast'),
        ),
    ]
