# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-29 16:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alpha', '0007_auto_20180529_2139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='image',
        ),
        migrations.AlterField(
            model_name='forecast',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 29, 21, 40, 56, 777540)),
        ),
    ]
