# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-31 07:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alpha', '0008_auto_20180529_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forecast',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 31, 12, 58, 46, 160642)),
        ),
    ]
