# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-20 08:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alpha', '0009_auto_20180620_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='identifier',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='invitefriends',
            name='status',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='identifier',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='forecast',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 20, 14, 24, 52, 165423)),
        ),
    ]
