# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-01 05:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alpha', '0009_auto_20180531_1258'),
    ]

    operations = [
        migrations.CreateModel(
            name='Approved',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
            options={
                'ordering': ['-name'],
                'verbose_name_plural': 'Approved',
            },
        ),
        migrations.CreateModel(
            name='Verified',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
            options={
                'ordering': ['-name'],
                'verbose_name_plural': 'Source',
            },
        ),
        migrations.AlterField(
            model_name='forecast',
            name='approved',
            field=models.ForeignKey(default='No', on_delete=django.db.models.deletion.CASCADE, to='alpha.Approved'),
        ),
        migrations.AlterField(
            model_name='forecast',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 1, 10, 31, 46, 141913)),
        ),
        migrations.AlterField(
            model_name='forecast',
            name='verified',
            field=models.ForeignKey(default='No', on_delete=django.db.models.deletion.CASCADE, to='alpha.Verified'),
        ),
        migrations.AlterField(
            model_name='forecast',
            name='won',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
