# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-01 05:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alpha', '0010_auto_20180601_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forecast',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 1, 10, 38, 13, 477550)),
        ),
    ]
