# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-01 07:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alpha', '0011_auto_20180601_1038'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='verified',
            options={'ordering': ['-name'], 'verbose_name_plural': 'Verified'},
        ),
        migrations.AlterField(
            model_name='forecast',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 1, 13, 6, 53, 442568)),
        ),
    ]
