# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-06 12:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alpha', '0012_auto_20180601_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forecast',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 6, 17, 35, 55, 804433)),
        ),
    ]
