# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-14 05:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alpha', '0012_auto_20180511_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='forecast',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='forecast',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 14, 11, 25, 22, 535451)),
        ),
    ]
