# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-07 09:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alpha', '0013_auto_20180606_1735'),
    ]

    operations = [
        migrations.CreateModel(
            name='Private',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
            options={
                'ordering': ['-name'],
                'verbose_name_plural': 'Approved',
            },
        ),
        migrations.AlterModelOptions(
            name='betting',
            options={'ordering': ['-bet_for'], 'verbose_name_plural': 'Points In Play'},
        ),
        migrations.AlterModelOptions(
            name='forecast',
            options={'ordering': ['-category'], 'verbose_name_plural': 'FORECAST'},
        ),
        migrations.AlterField(
            model_name='forecast',
            name='approved',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alpha.Approved'),
        ),
        migrations.AlterField(
            model_name='forecast',
            name='private',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alpha.Private'),
        ),
        migrations.AlterField(
            model_name='forecast',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 7, 15, 24, 6, 736371)),
        ),
        migrations.AlterField(
            model_name='forecast',
            name='verified',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alpha.Verified'),
        ),
    ]
