# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-14 05:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alpha', '0013_auto_20180514_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forecast',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 14, 11, 25, 30, 582320)),
        ),
    ]
