# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-14 06:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alpha', '0014_auto_20180514_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='forecast',
            name='market_fee',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='forecast',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 14, 11, 54, 52, 256547)),
        ),
    ]
