# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-14 06:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alpha', '0015_auto_20180514_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='betting',
            name='won',
            field=models.CharField(default='bet_for', max_length=100),
        ),
        migrations.AlterField(
            model_name='forecast',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 14, 12, 26, 42, 117827)),
        ),
    ]
