# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-21 10:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alpha', '0015_auto_20180620_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forecast',
            name='approved',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='alpha.Approved'),
        ),
        migrations.AlterField(
            model_name='forecast',
            name='private',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='alpha.Private'),
        ),
        migrations.AlterField(
            model_name='forecast',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 21, 10, 31, 41, 313875)),
        ),
        migrations.AlterField(
            model_name='forecast',
            name='verified',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='alpha.Verified'),
        ),
    ]
