# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-21 10:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alpha', '0016_auto_20180621_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forecast',
            name='created',
            field=models.DateField(default=datetime.datetime(2018, 6, 21, 10, 34, 32, 273113)),
        ),
        migrations.AlterField(
            model_name='forecast',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 21, 10, 34, 32, 272949)),
        ),
        migrations.AlterField(
            model_name='forecast',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='alpha.Status'),
        ),
    ]
