# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-14 06:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alpha', '0016_auto_20180514_1226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='betting',
            name='won',
        ),
        migrations.AddField(
            model_name='forecast',
            name='won',
            field=models.CharField(default='bet_for', max_length=100),
        ),
        migrations.AlterField(
            model_name='forecast',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 14, 12, 27, 49, 105252)),
        ),
    ]
