# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-16 06:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alpha', '0017_auto_20180514_1227'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.URLField()),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['-name'],
                'verbose_name_plural': 'Banner',
            },
        ),
        migrations.AlterField(
            model_name='forecast',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 16, 12, 23, 50, 842117)),
        ),
    ]
