# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-16 11:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socialaccount', '0008_socialaccount_fg_points_total'),
        ('alpha', '0018_auto_20180516_1223'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_date', models.DateField(auto_now=True)),
                ('txnid', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('amount', models.FloatField(blank=True, default=0.0, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socialaccount.SocialAccount')),
            ],
            options={
                'ordering': ['-user'],
                'verbose_name_plural': 'Order',
            },
        ),
        migrations.AlterField(
            model_name='forecast',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 16, 17, 19, 56, 468473)),
        ),
    ]
