# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-18 12:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('alpha', '0019_auto_20180516_1719'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forecast',
            name='created',
        ),
        migrations.AddField(
            model_name='forecast',
            name='created_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='forecast',
            name='created_time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='forecast',
            name='private',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='forecast',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 18, 17, 42, 53, 991997)),
        ),
    ]
