# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-18 12:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alpha', '0020_auto_20180518_1743'),
    ]

    operations = [
        migrations.RenameField(
            model_name='forecast',
            old_name='created_date',
            new_name='created',
        ),
        migrations.RemoveField(
            model_name='forecast',
            name='created_time',
        ),
        migrations.AlterField(
            model_name='forecast',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 18, 18, 25, 4, 481141)),
        ),
    ]
