# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-18 09:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Authentication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook_id', models.CharField(max_length=100)),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('mobile', models.CharField(blank=True, max_length=100, null=True)),
                ('gender', models.CharField(blank=True, max_length=100, null=True)),
                ('joining_points', models.IntegerField(default=0)),
                ('points_won', models.IntegerField(default=0)),
                ('points_earned', models.IntegerField(default=0)),
                ('points_lost', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now=True)),
                ('last_login', models.DateField(auto_now=True)),
                ('login_count', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-email'],
                'verbose_name_plural': 'Forecast Users',
            },
        ),
    ]
