# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-18 11:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_dailyfreepoints'),
    ]

    operations = [
        migrations.CreateModel(
            name='JoiningPoints',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Joining Bonus',
            },
        ),
        migrations.AlterModelOptions(
            name='dailyfreepoints',
            options={'ordering': ['-days'], 'verbose_name_plural': 'Daily Bonus'},
        ),
    ]
