# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-18 11:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_auto_20180718_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authentication',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
