# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-18 12:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_auto_20180718_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authentication',
            name='last_login',
            field=models.DateField(default=datetime.date(2018, 7, 18)),
        ),
    ]
