# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-19 05:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_auto_20180719_0528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authentication',
            name='facebook_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
