# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-19 06:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_auto_20180719_0559'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forecast',
            name='approved',
        ),
        migrations.AlterField(
            model_name='forecast',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='authentication.Status'),
        ),
        migrations.AlterField(
            model_name='forecast',
            name='won',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='authentication.Winning'),
        ),
    ]
