# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-19 09:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_auto_20180719_0608'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferralCodeRegistered',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referral_code', models.CharField(max_length=10)),
            ],
            options={
                'ordering': ['-referral_code'],
                'verbose_name_plural': 'Referral Code',
            },
        ),
        migrations.AddField(
            model_name='authentication',
            name='referral_code',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='forecast',
            name='private',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='authentication.Private'),
        ),
        migrations.AddField(
            model_name='referralcoderegistered',
            name='user_joined',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.Authentication'),
        ),
    ]
