# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-19 10:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0012_auto_20180719_1008'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferralCodePoints',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Referral Points',
            },
        ),
        migrations.AlterModelOptions(
            name='referralcoderegistered',
            options={'ordering': ['-date_joined'], 'verbose_name_plural': 'Referral Code'},
        ),
        migrations.AddField(
            model_name='referralcoderegistered',
            name='date_joined',
            field=models.DateField(auto_now=True),
        ),
    ]
