# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-19 10:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0013_auto_20180719_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referralcodepoints',
            name='points',
            field=models.CharField(max_length=100),
        ),
    ]
