# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-23 07:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0015_auto_20180723_0451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authentication',
            name='email',
            field=models.EmailField(default=1, max_length=254, unique=True),
            preserve_default=False,
        ),
    ]
