# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-23 10:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0018_auto_20180723_1021'),
    ]

    operations = [
        migrations.AddField(
            model_name='authentication',
            name='forecast_participated',
            field=models.IntegerField(default=0),
        ),
    ]
