# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-24 09:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0020_auto_20180724_0551'),
    ]

    operations = [
        migrations.CreateModel(
            name='HideForecast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(default=0)),
                ('forecast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.ForeCast')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.Authentication')),
            ],
            options={
                'ordering': ['-user'],
                'verbose_name_plural': 'Hidden Forecast',
            },
        ),
        migrations.CreateModel(
            name='MarketFee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField()),
            ],
            options={
                'ordering': ['-points'],
                'verbose_name_plural': 'Market Fee',
            },
        ),
        migrations.CreateModel(
            name='RateApp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(max_length=10)),
                ('feedback', models.CharField(max_length=1000)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.Authentication')),
            ],
            options={
                'ordering': ['-rating'],
                'verbose_name_plural': 'Application Rating',
            },
        ),
        migrations.CreateModel(
            name='ReportAbuseForecast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(default=0)),
                ('forecast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.ForeCast')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.Authentication')),
            ],
            options={
                'ordering': ['-user'],
                'verbose_name_plural': 'Report Abuse Forecast',
            },
        ),
        migrations.CreateModel(
            name='ShareForecast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField()),
            ],
            options={
                'ordering': ['-points'],
                'verbose_name_plural': 'Share Forecast Points',
            },
        ),
    ]
