# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-24 10:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0021_hideforecast_marketfee_rateapp_reportabuseforecast_shareforecast'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='forecast',
            options={'ordering': ['-category'], 'verbose_name_plural': 'Forecast'},
        ),
    ]
