# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-24 10:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0022_auto_20180724_1001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='identifier',
        ),
    ]
