# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-24 10:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0023_remove_category_identifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='identifier',
            field=models.IntegerField(default=0),
        ),
    ]
