# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-24 11:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0024_category_identifier'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='forecast',
            options={'ordering': ['-expire'], 'verbose_name_plural': 'Forecast'},
        ),
    ]
