# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-24 11:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0025_auto_20180724_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='authentication',
            name='forecast_played',
            field=models.IntegerField(default=0),
        ),
    ]
