# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-02 04:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0027_auto_20180802_0436'),
    ]

    operations = [
        migrations.AddField(
            model_name='authentication',
            name='referral_status',
            field=models.IntegerField(default=0),
        ),
    ]
