# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-02 04:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authentication', '0028_authentication_referral_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authentication',
            options={'ordering': ['-created']},
        ),
        migrations.RemoveField(
            model_name='authentication',
            name='email',
        ),
        migrations.RemoveField(
            model_name='authentication',
            name='facebook_id',
        ),
        migrations.RemoveField(
            model_name='authentication',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='authentication',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='authentication',
            name='mobile',
        ),
        migrations.AddField(
            model_name='authentication',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
