# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-02 05:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0029_auto_20180802_0451'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authentication',
            options={'ordering': ['-email']},
        ),
        migrations.RemoveField(
            model_name='authentication',
            name='user',
        ),
        migrations.AddField(
            model_name='authentication',
            name='email',
            field=models.EmailField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='authentication',
            name='facebook_id',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='authentication',
            name='first_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='authentication',
            name='gender',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='authentication',
            name='last_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='authentication',
            name='mobile',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
