# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-02 06:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0030_auto_20180802_0501'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authentication',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='authentication',
            name='mobile',
        ),
        migrations.RemoveField(
            model_name='userinterest',
            name='interest',
        ),
        migrations.AddField(
            model_name='userinterest',
            name='interest',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='authentication.SubCategory'),
            preserve_default=False,
        ),
    ]
