# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-03 07:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0031_auto_20180802_0617'),
    ]

    operations = [
        migrations.AddField(
            model_name='authentication',
            name='interest_status',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='authentication',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='authentication',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='authentication',
            name='last_login',
            field=models.DateField(default=datetime.date(2018, 8, 3)),
        ),
        migrations.AlterField(
            model_name='authentication',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
