# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-06 06:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0032_auto_20180803_0704'),
    ]

    operations = [
        migrations.CreateModel(
            name='Verified',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
            options={
                'ordering': ['-name'],
                'verbose_name_plural': 'Verified',
            },
        ),
        migrations.AlterField(
            model_name='authentication',
            name='last_login',
            field=models.DateField(default=datetime.date(2018, 8, 6)),
        ),
    ]
