# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-08 06:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0033_auto_20180806_0649'),
    ]

    operations = [
        migrations.AddField(
            model_name='authentication',
            name='forecast_created',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='authentication',
            name='last_login',
            field=models.DateField(default=datetime.date(2018, 8, 8)),
        ),
    ]
