# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-08 07:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0034_auto_20180808_0647'),
    ]

    operations = [
        migrations.RenameField(
            model_name='authentication',
            old_name='forecast_played',
            new_name='points_lost_private',
        ),
        migrations.RenameField(
            model_name='authentication',
            old_name='points_lost',
            new_name='points_lost_public',
        ),
        migrations.RenameField(
            model_name='authentication',
            old_name='points_won',
            new_name='points_won_private',
        ),
        migrations.AddField(
            model_name='authentication',
            name='points_won_public',
            field=models.IntegerField(default=0),
        ),
    ]
