# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-09 06:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0035_auto_20180808_0738'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-user'],
                'verbose_name_plural': 'Login Status',
            },
        ),
        migrations.RenameField(
            model_name='authentication',
            old_name='points_lost_public',
            new_name='forecast_played',
        ),
        migrations.AlterField(
            model_name='authentication',
            name='last_login',
            field=models.DateField(default=datetime.date(2018, 8, 9)),
        ),
        migrations.AddField(
            model_name='loginstatus',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.Authentication'),
        ),
    ]
