# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-22 06:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0037_authentication_points_lost_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authentication',
            name='last_login',
            field=models.DateField(default=datetime.date(2018, 8, 22)),
        ),
    ]
