# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-22 07:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0038_auto_20180822_0630'),
    ]

    operations = [
        migrations.CreateModel(
            name='RedeemPoints',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('redeem_points', models.IntegerField()),
                ('redeem_to', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Redeem Points',
            },
        ),
    ]
