# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-23 12:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0040_auto_20180823_1105'),
    ]

    operations = [
        migrations.CreateModel(
            name='SendNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(max_length=1000)),
                ('url', models.URLField()),
                ('status', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Send Notification',
            },
        ),
    ]
