# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-24 05:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0042_auto_20180824_0515'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPanel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Forecast Guru. Predict future.', max_length=1000)),
                ('message', models.CharField(max_length=1000)),
                ('url', models.URLField()),
                ('status', models.IntegerField(default=0)),
                ('created', models.DateField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.Authentication')),
            ],
            options={
                'ordering': ['-user'],
                'verbose_name_plural': 'Notification Panel',
            },
        ),
        migrations.CreateModel(
            name='NotificationUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscriber_id', models.CharField(max_length=1000)),
                ('created', models.DateField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.Authentication')),
            ],
            options={
                'ordering': ['-user'],
                'verbose_name_plural': 'Notification User',
            },
        ),
        migrations.CreateModel(
            name='SendNotificationAll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('message', models.CharField(max_length=1000)),
                ('url', models.URLField()),
                ('status', models.IntegerField(default=0)),
                ('created', models.DateField(auto_now=True)),
            ],
            options={
                'ordering': ['-created'],
                'verbose_name_plural': 'Notification All',
            },
        ),
    ]
