# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-09-03 14:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0043_notificationpanel_notificationuser_sendnotificationall'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authentication',
            name='last_login',
            field=models.DateField(default=datetime.date(2018, 9, 3)),
        ),
    ]
