# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-04 13:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0044_auto_20180903_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authentication',
            name='last_login',
            field=models.DateField(default=datetime.date(2018, 9, 4)),
        ),
    ]
